---
- name: delegate a task
  hosts: my_hosts
  gather_facts: false
  tasks:
    - name: collect the hostname
      command: hostname
      changed_when: false
      delegate_to: workstation.lab.example.com
      register: hostname_out

    - name: display the hostname
      ansible.builtin.debug:
        var: hostname_out.stdout
...
