download_url: https://hub.lab.example.com/api/galaxy/v3/plugin/ansible/content/community/collections/artifacts/containers-podman-1.10.1.tar.gz
format_version: 1.0.0
name: podman
namespace: containers
server: https://hub.lab.example.com/api/galaxy/content/community/
signatures: []
version: 1.10.1
version_url: /api/galaxy/content/community/v3/plugin/ansible/content/community/collections/index/containers/podman/versions/1.10.1/
